// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr3IldtsXg4-B6MXGtMo-rphX5UH4Pigg',
    appId: '1:516352908658:web:fe3e08bb07df316babd1eb',
    messagingSenderId: '516352908658',
    projectId: 'brostaky-3c17c',
    authDomain: 'brostaky-3c17c.firebaseapp.com',
    storageBucket: 'brostaky-3c17c.firebasestorage.app',
    measurementId: 'G-SHVJSFZWYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABmtfxaKM-AMDaH9TktYoHp7N2fNIQt3E',
    appId: '1:516352908658:android:550097f2688e6502abd1eb',
    messagingSenderId: '516352908658',
    projectId: 'brostaky-3c17c',
    storageBucket: 'brostaky-3c17c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyxnQHtzhLFg9VUiBaxb_cfzQdp0fhwSI',
    appId: '1:516352908658:ios:65822f49b60f2052abd1eb',
    messagingSenderId: '516352908658',
    projectId: 'brostaky-3c17c',
    storageBucket: 'brostaky-3c17c.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyxnQHtzhLFg9VUiBaxb_cfzQdp0fhwSI',
    appId: '1:516352908658:ios:65822f49b60f2052abd1eb',
    messagingSenderId: '516352908658',
    projectId: 'brostaky-3c17c',
    storageBucket: 'brostaky-3c17c.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr3IldtsXg4-B6MXGtMo-rphX5UH4Pigg',
    appId: '1:516352908658:web:fdf8ee7db8a69becabd1eb',
    messagingSenderId: '516352908658',
    projectId: 'brostaky-3c17c',
    authDomain: 'brostaky-3c17c.firebaseapp.com',
    storageBucket: 'brostaky-3c17c.firebasestorage.app',
    measurementId: 'G-K58PP8LN6M',
  );

}